### ISSUE TITLE
Refresh fails when Workspace data store item selected

### ISSUE THREAD

**Issue by dakcarto** [boundlessgeo/suite-qgis-plugin#170]
Refresh button on panel's toolbar fails when **GeoServer Workspaces** data store item selected:

![opengeo-expl_refresh-store](https://cloud.githubusercontent.com/assets/1295919/6281207/36b6e89e-b879-11e4-8eb2-2d5bdc70a879.png)

Fails with:

```
Traceback (most recent call last):
  File "/Users/user/.qgis2/python/plugins/opengeo/gui/explorertree.py", line 51, in 
    refreshAction.triggered.connect(lambda: item.refreshContent(self.explorer))
  File "/Users/user/.qgis2/python/plugins/opengeo/gui/exploreritems.py", line 18, in refreshContent
    self.element.refresh()
  File "build/bdist.macosx-10.9-x86_64/egg/geoserver/support.py", line 168, in refresh
    self.fetch()
  File "build/bdist.macosx-10.9-x86_64/egg/geoserver/support.py", line 161, in fetch
    self.dom = self.catalog.get_xml(self.href)

  ...

  File "build/bdist.macosx-10.9-x86_64/egg/geoserver/store.py", line 37, in href
    ["workspaces", self.workspace.name, "datastores", self.name + ".xml"])
  File "build/bdist.macosx-10.9-x86_64/egg/geoserver/support.py", line 57, in getter
    self.fetch()
  File "build/bdist.macosx-10.9-x86_64/egg/geoserver/support.py", line 161, in fetch
    self.dom = self.catalog.get_xml(self.href)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by dakcarto** [comment]
Fixed with e5256a7
