### ISSUE TITLE
An error occures when adding new catalog

### ISSUE THREAD

**Issue by JogicPogic** [boundlessgeo/suite-qgis-plugin#189]
An error occures when adding new catalog:
![opengeo explorer error](https://cloud.githubusercontent.com/assets/13277024/12885789/7a0900aa-ce8a-11e5-8842-233d03d658cd.png)

**Comment by philnagel** [comment]
I have the same issue. This is the error message:An error has occured while executing Python code: 

AttributeError: 'keypasssupported' is not a Qt property or a signal 
Traceback (most recent call last):
  File "C:/Users/philippn/.qgis2/python/plugins\opengeo\gui\gsexploreritems.py", line 231, in 
    createCatalogAction.triggered.connect(lambda: self.addGeoServerCatalog(explorer))
  File "C:/Users/philippn/.qgis2/python/plugins\opengeo\gui\gsexploreritems.py", line 235, in addGeoServerCatalog
    dlg = DefineCatalogDialog(explorer)
  File "C:/Users/philippn/.qgis2/python/plugins\opengeo\gui\dialogs\catalogdialog.py", line 14, in __init__
    self.initGui()
  File "C:/Users/philippn/.qgis2/python/plugins\opengeo\gui\dialogs\catalogdialog.py", line 92, in initGui
    self.certWidget = QgsAuthConfigSelect( keypasssupported = False)
AttributeError: 'keypasssupported' is not a Qt property or a signal


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.12.2-Lyon Lyon, b403532 

Python Path:
C:/OSGEO4~1/apps/qgis/./python/plugins\processing
C:/OSGEO4~1/apps/qgis/./python
C:/Users/philippn/.qgis2/python
C:/Users/philippn/.qgis2/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\requests-2.0.1-py2.7.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\raven-3.5.1-py2.7.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\nose_html-1.1-py2.7.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\gsconfig-0.6.9-py2.7.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\gsimporter-0.1-py2.7.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\python_dateutil-2.2-py2.7.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\six-1.7.3-py2.7.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\lxml-3.3.5-py2.7-win32.egg
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs\httplib2-0.9-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\six-1.3.0-py2.7.egg
C:\OSGEO4~1\bin\python27.zip
C:\OSGEO4~1\apps\Python27\DLLs
C:\OSGEO4~1\apps\Python27\lib
C:\OSGEO4~1\apps\Python27\lib\plat-win
C:\OSGEO4~1\apps\Python27\lib\lib-tk
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python27
C:\OSGEO4~1\apps\Python27\lib\site-packages
C:\OSGEO4~1\apps\Python27\lib\site-packages\PIL
C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin
C:\OSGEO4~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\OSGEO4~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/philippn/.qgis2//python
C:\Users\philippn\.qgis2\python\plugins\opengeo\ext-libs
C:\OSGEO4~1\apps\qgis\python\plugins\fTools\tools

QGIS Version

**Comment by dakcarto** [comment]
Hi. This is from using the <= version 0.7.x of the plugin with a version of QGIS other than Boundless QGIS 2.8.3 release, which has PKI support, or a QGIS community 2.12+.

This has been fixed with version 0.8.0 of the plugin, which we are testing right now for release ASAP.

**Comment by elpaso** [comment]
Temporary fix for QGIS master: change line 94 of `.qgis2/python/plugins/opengeo/gui/dialogs/catalogdialog.py` adding `TypeError` to catched exceptions, from
```
        try:
            self.certWidget = QgsAuthConfigSelect( keypasssupported = False)
            self.tabWidget.addTab(self.certWidget, "Configurations")
        except NameError:
            #for QGIS without PKI support
            pass
```
to
```
        try:
            self.certWidget = QgsAuthConfigSelect( keypasssupported = False)
            self.tabWidget.addTab(self.certWidget, "Configurations")
        except TypeError, NameError:
            #for QGIS without PKI support
            pass
```

**Comment by dakcarto** [comment]
Sorry for the delay. We are now doing final testing on a v0.8.0 maintenance release, which will be posted to the qgis.boundlessgeo.com plugin repository soon (within the next week).

**Comment by dakcarto** [comment]
OpenGeo Explorer v0.8.0 has been released. Please verify this issue has been fixed for you. Thanks.
